### ISSUE TITLE
Error response getting {} 

### ISSUE THREAD

**Issue by arilsonkarmo** [appfeel/node-pushnotifications#74] opened 2018-02-21 18:43 UTC
Gettin this for result in apn

[{"method":"apn","success":0,"failure":1,"message":[{"regId":"EHAUOOIERYYE18762131H27123H23FC312H12312312L3F12V32G1V","error":{}}]}]

if failure why errors coming an empty object?

Thank's

**Comment by alex-friedl** [comment] 2018-02-27 19:23
Duplicate of https://github.com/appfeel/node-pushnotifications/issues/34 and https://github.com/appfeel/node-pushnotifications/issues/38 ?

**Comment by alex-friedl** [comment] 2018-04-08 14:02
Closing this as a duplicate of the existing issues for this

**Closed by alex-friedl** 2018-04-08 14:02 UTC
Labels: duplicate
