### ISSUE TITLE
TypeError: apn.Connection is not a function

### ISSUE THREAD

**Issue by JohanWillfred** [appfeel/node-pushnotifications#18] opened 2016-10-05 13:53 UTC
Hi! Error after modules update. The problem can be reproduced on attempt to send APNS push.
Looks like problem in updated APN library

**Comment by ser-j** [comment] 2016-10-07 08:01
I have the same issue here.

Looks like the problem in node-apn module, in updated version (2.1.1) it hasn't connection.js at all.

Seems we have to change package.json:

"dependencies": {
    "apn": "*",

to 

"dependencies": {
    "apn": "^1.7.8",

**Comment by JohanWillfred** [comment] 2016-10-07 08:29
@ser-j Yes, it will fix the problem, but in my case (node-lambda) it is better to use APN directly. 
And as I saw there are all dependencies with "*", so I think that it will be better to change lib, coz same situation can happen again with any of depended modules.

Thank you for your response)

**Comment by Ryanthegiantlion** [comment] 2016-10-10 06:20
This is a duplicate of #17 and should probably be closed.

**Comment by appfeel** [comment] 2016-10-14 17:33
Yes, thanks solved in https://github.com/appfeel/node-pushnotifications/pull/11

**Closed by appfeel** 2016-10-14 17:33 UTC
