### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by bjoern2610** [appfeel/node-pushnotifications#126] opened 2020-02-15 01:18 UTC
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added. Use emitter.setMaxListeners() to increase limit

const results = await push.send(devices, data);
console.log('Push results', results);

Why i get memory leak detected?

What i need to change?

**Comment by alex-friedl** [comment] 2020-02-15 12:34
Hm, possible duplicate of https://github.com/appfeel/node-pushnotifications/issues/70 ?
We thought/hoped the issue was fixed. Which version of the library are you using? the most recent one?

**Comment by bjoern2610** [comment] 2020-02-15 12:37
I have the library node-pushnotifications@1.2.1. I needed to add this to solve error message. But is it the right solution?

require('events').EventEmitter.defaultMaxListeners = 0;

**Comment by alex-friedl** [comment] 2020-02-15 12:44
I wouldn't recommend that solution, since it changes the default value for _all_ event emitters in your application (https://nodejs.org/api/events.html#events_eventemitter_defaultmaxlisteners)

Not sure myself how to proceed with this issue. Maybe the warning can even safely be ignored? Do oyu have profiling data on the memory usage of your application?

**Comment by bjoern2610** [comment] 2020-02-15 12:48
Maybe the warning can even safely be ignored? 

Can i really ignore this? I have only 12 deviceIds in the DB and sending. If i need to send 10k what will happen?

**Comment by bjoern2610** [comment] 2020-02-16 09:34
Somebody here?

**Comment by alex-friedl** [comment] 2020-02-16 16:55
Sorry. From what I understand it's an issue with node-apn and nothing we can fix in this library? Did you open an issue there?

**Comment by bjoern2610** [comment] 2020-02-16 18:53
OK, let me do a request issue on node-apn.

**Comment by KBSchmidt** [comment] 2020-12-02 12:26
@bjoern2610 do you still experince this issue with the latest release?

**Comment by alex-friedl** [comment] 2020-12-03 21:37
Closing this for inactivity, as it does not seem to be an issue for any other users. Please re-open if issue persists

**Closed by alex-friedl** 2020-12-03 21:37 UTC
