### ISSUE TITLE
Wrong message on apn

### ISSUE THREAD

**Issue by w4ller** [appfeel/node-pushnotifications#9] opened 2016-07-17 13:47 UTC
For Ios:
when I try to send an apn notification with basic setup and basic data 
    title: "This is a title",
    message: "This is the body",
    otherfields: ''

I get this result:
{ device: 'ios', message: 'completed' }
Otherwise msg on device:
undefined Message: This is a title

**Comment by appfeel** [comment] 2016-10-14 18:15
Duplicate of https://github.com/appfeel/node-pushnotifications/issues/8, fixed in https://github.com/appfeel/node-pushnotifications/commit/5090a96dee49d7bfb9dddb91d5c8bef1d1adb25b

**Closed by appfeel** 2016-10-14 18:15 UTC
